# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compost', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measure',
            new_name='Measurement',
        ),
    ]
